# Generated by Django 2.2.12 on 2021-07-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscMat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oper', models.CharField(max_length=100)),
                ('app', models.CharField(max_length=100)),
                ('group_id', models.EmailField(max_length=254)),
                ('person1', models.CharField(max_length=100)),
                ('person2', models.CharField(max_length=100)),
                ('person3', models.CharField(max_length=100)),
                ('person4', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'escalation',
            },
        ),
    ]
