# Generated by Django 2.2.12 on 2021-07-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escmat',
            name='app_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
