# Generated by Django 2.2.12 on 2021-07-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_escmat_app_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escmat',
            old_name='app_name',
            new_name='aname',
        ),
    ]
