# Generated by Django 2.2.12 on 2021-07-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210703_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escmat',
            name='aname',
            field=models.CharField(max_length=100),
        ),
    ]
