# Generated by Django 2.2.12 on 2021-07-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210703_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escmat',
            name='app',
        ),
        migrations.AddField(
            model_name='escmat',
            name='ari',
            field=models.CharField(default='SOME', max_length=100),
        ),
    ]
