# Generated by Django 2.2.12 on 2021-07-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20210703_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escmat',
            name='ari',
            field=models.CharField(max_length=100),
        ),
    ]
