# Generated by Django 2.2.12 on 2021-08-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_sop'),
    ]

    operations = [
        migrations.CreateModel(
            name='train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=100, unique=True)),
                ('product', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='static/pdf/training')),
            ],
            options={
                'db_table': 'train\t',
            },
        ),
        migrations.AlterField(
            model_name='sop',
            name='doc',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sop',
            name='pdf',
            field=models.FileField(upload_to='static/pdf/sop'),
        ),
    ]
