# Generated by Django 2.2.12 on 2021-08-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20210802_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('month', models.CharField(max_length=5)),
                ('level', models.CharField(max_length=5)),
                ('imag', models.FileField(upload_to='static/shift')),
            ],
            options={
                'db_table': 'shift',
            },
        ),
        migrations.AlterModelTable(
            name='train',
            table='train',
        ),
    ]
