# Generated by Django 2.2.12 on 2021-08-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20210802_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='month',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='shift',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
