# Generated by Django 2.2.12 on 2021-08-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20210802_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='year',
            field=models.TextField(max_length=4),
        ),
    ]
