# Generated by Django 2.2.12 on 2021-08-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20210802_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='year',
        ),
    ]
