# Generated by Django 2.2.12 on 2021-08-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_shift_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
